name:                puzzle
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/dsanno/haskell-mathematics-puzzlepuzzle#readme
license:             MIT
author:              Daiki Sanno
maintainer:          daiki.sanno@gmail.com
copyright:           2018 © Daiki Sanno
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - time

executables:
  puzzle:
    source-dirs:
      - src
      - src/lib
      - src/01-palindrome-number
      - src/02-calculator
      - src/03-flip-card
      - src/04-cut-stick
      - src/05-money-exchange
      - src/06-collatz
      - src/07-binary-date
      - src/08-robot-cleaner
    main:             Main.hs

tests:
  puzzle-test:
    source-dirs:      test
    main:             Driver2.hs
    dependencies:
      - tasty
      - tasty-discover
